# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_my_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_trend',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='my_trend',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
